### ISSUE TITLE
Warning: findDOMNode

### ISSUE THREAD

**Issue by boostup** [boostup/react-spotify-clone-app#3]
I keep seeing this issue in the devtools console :

`index.js:1 Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node`

These are the top elements of the exception stack :+1: 
```
   at div
    at Paper (http://localhost:3000/static/js/0.chunk.js:19930:23)
    at WithStyles(ForwardRef(Paper)) (http://localhost:3000/static/js/0.chunk.js:39675:31)
    at Transition (http://localhost:3000/static/js/0.chunk.js:85741:30)
    at Grow (http://localhost:3000/static/js/0.chunk.js:12671:24)
```

**Comment by boostup** [comment]
This indicates that the problem comes from Material UI Elements like `Paper`, `WithStyles`.  It seems Material UI is using a deprecated `findDOMNode` function, and React Strict Mode is not happy about it.

**In fact, I can confirm that this console warning appear whenever clicking on the avatar to open the dropdown menu, which is all coming from the material UI libary.**

[React docs](https://reactjs.org/docs/strict-mode.html#warning-about-deprecated-finddomnode-usage) mentions this :

> Warning about deprecated findDOMNode usage
React used to support findDOMNode to search the tree for a DOM node given a class instance. Normally you don’t need this because you can attach a ref directly to a DOM node.

> findDOMNode can also be used on class components but this was breaking abstraction levels by allowing a parent to demand that certain children was rendered. It creates a refactoring hazard where you can’t change the implementation details of a component because a parent might be reaching into its DOM node. findDOMNode only returns the first child, but with the use of Fragments, it is possible for a component to render multiple DOM nodes. findDOMNode is a one time read API. It only gave you an answer when you asked for it. If a child component renders a different node, there is no way to handle this change. Therefore findDOMNode only worked if components always return a single DOM node that never changes.

> You can instead make this explicit by passing a ref to your custom component and pass that along to the DOM using ref forwarding.

> You can also add a wrapper DOM node in your component and attach a ref directly to it.

My understanding is that Strict Mode is for dev env only, and it is a tool help warn devs about deprecation, and hence, this console warning will not show up in production.

In addition, and most importantly, **since this causes no issue to the app itself, I will go ahead and close this issue.**
